###  Create student
POST localhost:8080/student
Content-Type: application/json

{
  "name": "Anvar",
  "surname": "Aliyev",
  "level": 2,
  "age": 19,
  "gender": "MALE"
}

### Student get all
GET localhost:8080/student

###Student  byId
GET localhost:8080/student/18

### Student update
PUT localhost:8080/student/14
Content-Type: application/json

{
  "name": "Anvar",
  "surname": "Aliyev",
  "level": 2,
  "age": 19,
  "gender": "MALE"
}

### Student delete
DELETE localhost:8080/student/16

### Student by name
GET localhost:8080/student/by-name/Anvar

### Student by surname
GET localhost:8080/student/by-surname/Aliyev

### Student by age
GET localhost:8080/student/by-age/20

### Student by level
GET localhost:8080/student/by-level/2

### Student by gender
GET localhost:8080/student/by-gender/MALE

### Student by date
GET localhost:8080/student/given-date?date=2025-04-24

### Student by dates
GET localhost:8080/student/given-dates?fromDate=2025-04-23&toDate=2025-04-24